#%RAML 1.0 DataType
description: Users from mainframe

properties:
  firstName:
    description: Name of the user
    type: string
  lastName:
    description: Last name of the user
    type: string
  age:
    type: integer
    description: Age of user
  createdOn?:
    type: datetime
  updatedOn?:
    type: datetime