#%RAML 1.0 NamedExample
users:
  - firstName: Harry
    lastName: Potter
    age: 30
    createdOn: 2018-06-01T11:12:00Z
  - firstName: Ron
    lastName: Wesley
    age: 32
    createdOn: 2018-06-01T11:12:00Z