name: Publish to Exchange

on: workflow_dispatch

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
    - name: Install Anypoint CLI
      run: |
          npm install -g anypoint-cli@latest
    - name: Publish API to Exchange
      run: |
          export ANYPOINT_USERNAME=${{ secrets.ANYPOINT_USERNAME }}
          export ANYPOINT_PASSWORD=${{ secrets.ANYPOINT_PASSWORD }}
          export ANYPOINT_ENV=Sandbox
          export API_NAME=oracle-system-api
          export ASSET_ID=$(mvn help:evaluate -Dexpression=project.name -q -DforceStdout -f $API_NAME/pom.xml)
          export ASSET_VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout -f $API_NAME/pom.xml)
          echo $ASSET_ID-$ASSET_VERSION
          anypoint-cli exchange asset upload --clssifier raml --apiVersion v1 --name 3a273add-4c00-4035-b500-8c6cb0607301/$ASSET_ID $API_NAME/src/main/resources/api
