# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Design Center Downloaded

on: workflow_dispatch

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
    - name: Install Anypoint CLI
      run: |
          npm install -g anypoint-cli@latest
    - name: Publish API to Exchange
      run: |
          export ANYPOINT_USERNAME=${{ secrets.ANYPOINT_USERNAME }}
          export ANYPOINT_PASSWORD=${{ secrets.ANYPOINT_PASSWORD }}
          export ANYPOINT_ENV=Sandbox
          export API_NAME=demo-system-api
          mvn help:evaluate -Dexpression=project.version -q -DforceStdout -f oracle-system-api/pom.xml
